In [1]:
import numpy as np

# 1.通过list创建

In [2]:
a = np.array([[1, 2, 3], [2, 3, 4]])
a

array([[1, 2, 3],
       [2, 3, 4]])

In [3]:
a.shape # 查看数组形状，是一个2行、3列的数组

(2, 3)

# 2.创建常见数组

In [4]:
np.zeros((4, 5)) # 创建指定形状，元素全为0的数组

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
np.ones((2, 3, 4)) # 元素全为1的数组

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [6]:
np.arange(1, 10, 2) # 创建等差数列，参数为(start, end, step)

array([1, 3, 5, 7, 9])

In [7]:
np.linspace(0, 2, 5) # 创建等差数列，参数为(start, end, number)

array([0. , 0.5, 1. , 1.5, 2. ])

# 3.指定数据类型

In [8]:
a.dtype # 查看数组数据类型

dtype('int64')

In [9]:
x = np.ones((2, 3), dtype=np.float32) # 创建数组时指定数据类型
x.dtype

dtype('float32')

In [10]:
x = x.astype(np.float64) # 通过astype改变数据类型，必须赋值才可以
x.dtype

dtype('float64')

# 4.随机数组

In [11]:
np.random.random(10), np.random.rand(3, 2) # 指定size的[0, 1)间均匀分布

(array([0.6935654 , 0.2382558 , 0.68075565, 0.07201349, 0.2580062 ,
        0.35204594, 0.96130437, 0.51761438, 0.42688966, 0.88846977]),
 array([[0.49720368, 0.47991355],
        [0.62342584, 0.99663937],
        [0.15549435, 0.78503571]]))

In [12]:
np.random.randn(2, 3) # 标准正态分布

array([[-0.28914392,  0.84529568, -1.50217661],
       [ 0.13777773, -1.25421842,  0.56733085]])

In [13]:
np.random.normal(1, 2, (2, 2)) # 正态分布，参数为(mean, std, size)

array([[ 1.76621615,  2.10967644],
       [-0.60624468,  1.44969107]])

In [14]:
np.random.multivariate_normal([0, 0], [[2, 1], [1, 3]], 10) # 多维正态分布，参数为(mean, covariance, size)

array([[-1.58488416, -0.32131641],
       [ 1.2515103 , -1.9869109 ],
       [-1.47261231, -3.98163716],
       [ 1.20022357,  2.77117939],
       [ 1.70814093,  2.0469959 ],
       [-0.40989814, -2.09239026],
       [-0.33167331,  1.06644579],
       [-1.26054509, -0.77222506],
       [-0.41452086, -2.65416042],
       [ 0.84579329,  0.04219217]])

In [15]:
np.random.randint(0, 4, 10) # 随机整数，参数为(low, high, size)

array([0, 2, 1, 3, 1, 1, 3, 3, 0, 3])

In [16]:
np.random.seed(1) # 固定随机数种子，有助于复现
np.random.random() # 固定随机数种子为1后，下一个np.random.random()必定为0.417022004702574

0.417022004702574