In [1]:
import numpy as np

# 1.通过list创建

In [2]:
a = np.array([[1, 2, 3], [2, 3, 4]])
a

array([[1, 2, 3],
       [2, 3, 4]])

In [3]:
a.shape # 查看数组形状，是一个2行、3列的数组

(2, 3)

# 2.创建常见数组

In [4]:
np.zeros((4, 5)) # 创建指定形状，元素全为0的数组

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
np.ones((2, 3, 4)) # 元素全为1的数组

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [6]:
np.arange(1, 10, 2) # 创建等差数列，参数为(start, end, step)

array([1, 3, 5, 7, 9])

In [7]:
np.linspace(0, 2, 5) # 创建等差数列，参数为(start, end, number)

array([0. , 0.5, 1. , 1.5, 2. ])

# 3.指定数据类型

In [8]:
a.dtype # 查看数组数据类型

dtype('int64')

In [9]:
x = np.ones((2, 3), dtype=np.float32) # 创建数组时指定数据类型
x.dtype

dtype('float32')

In [10]:
x = x.astype(np.float64) # 通过astype改变数据类型，必须赋值才可以
x.dtype

dtype('float64')

# 4.随机数组

In [11]:
np.random.random(10), np.random.rand(3, 2) # 指定size的[0, 1)间均匀分布

(array([0.56705653, 0.62408795, 0.25216265, 0.55974146, 0.93557329,
        0.13439719, 0.22449223, 0.90979085, 0.9826664 , 0.21847333]),
 array([[0.2941271 , 0.55525308],
        [0.334125  , 0.61554745],
        [0.81251763, 0.7813304 ]]))

In [12]:
np.random.randn(2, 3) # 标准正态分布

array([[ 1.29760211, -1.23090597, -1.26806806],
       [-1.66848968, -0.532497  , -0.09957237]])

In [13]:
np.random.normal(1, 2, (2, 2)) # 正态分布，参数为(mean, std, size)

array([[ 1.48594109, -3.41908522],
       [-0.14954831,  0.39968962]])

In [14]:
np.random.randint(0, 4, 10) # 随机整数，参数为(low, high, size)

array([2, 2, 3, 1, 2, 1, 2, 2, 3, 1])

In [15]:
np.random.seed(1) # 固定随机数种子，有助于复现
np.random.random() # 固定随机数种子为1后，下一个np.random.random()必定为0.417022004702574

0.417022004702574