In [1]:
import numpy as np

# 1.索引

In [2]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
a[0, 1], a[0][1] # 获取数组第i个值

(2, 2)

In [4]:
a[1, -1] = 10 # 通过负值索引获得数组末尾的值，修改元素值
a

array([[ 1,  2,  3],
       [ 4,  5, 10]])

In [5]:
a[1] # 第2行

array([ 4,  5, 10])

# 2.数组切片

In [6]:
a[:, 0] # 第1列

array([1, 4])

In [7]:
a[: , : 2] # 即切行，也切列

array([[1, 2],
       [4, 5]])

# 3.reshape函数

In [8]:
x = np.arange(12)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [9]:
x.reshape(3, 4) # 3行4列的数组

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
x.reshape(2, 3, -1) # 用-1来自动计算

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [11]:
x = x.reshape(-1, 2) # 改变数组形状
x

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [12]:
x.flatten(), x.reshape(-1) # flatten等价于reshape(-1)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]))