In [1]:
import numpy as np

# 1.索引

In [2]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
a[0, 1], a[0][1] # 获取数组第i个值

(2, 2)

In [4]:
a[1, -1] = 10 # 通过负值索引获得数组末尾的值，修改元素值
a

array([[ 1,  2,  3],
       [ 4,  5, 10]])

In [5]:
a[1] # 第2行

array([ 4,  5, 10])

# 2.数组切片

In [6]:
a[:, 0] # 第1列

array([1, 4])

In [7]:
a[: , : 2] # 即切行，也切列

array([[1, 2],
       [4, 5]])