In [1]:
import numpy as np

# 1.reshape函数

In [2]:
x = np.arange(12)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
x.reshape(3, 4) # 3行4列的数组

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
x.reshape(2, 3, -1) # 用-1来自动计算

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [5]:
x = x.reshape(-1, 2) # 改变数组形状
x

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [6]:
x.flatten(), x.reshape(-1) # flatten等价于reshape(-1)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]))

# 2.数组拼接

In [7]:
x = np.arange(6).reshape(2, 3)
y = np.ones((2, 3))

In [8]:
np.concatenate((x, y)) # 垂直向拼接

array([[0., 1., 2.],
       [3., 4., 5.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
np.concatenate((x, y), axis=1) # 水平向拼接

array([[0., 1., 2., 1., 1., 1.],
       [3., 4., 5., 1., 1., 1.]])

In [10]:
np.vstack((x, y)) # 垂直向拼接

array([[0., 1., 2.],
       [3., 4., 5.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.hstack((x, y)) # 水平向拼接

array([[0., 1., 2., 1., 1., 1.],
       [3., 4., 5., 1., 1., 1.]])