In [1]:
import numpy as np

# 1.数组间运算

In [2]:
a = np.arange(-2, 4).reshape(3, 2)
b = np.ones((3, 2))
a, b

(array([[-2, -1],
        [ 0,  1],
        [ 2,  3]]),
 array([[1., 1.],
        [1., 1.],
        [1., 1.]]))

In [3]:
a + b # 加法，element-wise

array([[-1.,  0.],
       [ 1.,  2.],
       [ 3.,  4.]])

In [4]:
a // b # 整除

array([[-2., -1.],
       [ 0.,  1.],
       [ 2.,  3.]])

In [5]:
a % b # 取余

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [6]:
a ** b # 指数

array([[-2., -1.],
       [ 0.,  1.],
       [ 2.,  3.]])

# 2.常用函数

In [7]:
np.abs(a) # 取绝对值

array([[2, 1],
       [0, 1],
       [2, 3]])

In [8]:
np.power(a, 3) # 3次方

array([[-8, -1],
       [ 0,  1],
       [ 8, 27]])

In [9]:
np.sin(a) # 三角函数 

array([[-0.90929743, -0.84147098],
       [ 0.        ,  0.84147098],
       [ 0.90929743,  0.14112001]])

In [10]:
np.exp(a) # 指数函数

array([[ 0.13533528,  0.36787944],
       [ 1.        ,  2.71828183],
       [ 7.3890561 , 20.08553692]])

In [11]:
np.log(b) # 对数函数

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

# 3.广播

In [12]:
x = np.arange(1, 3)

In [13]:
x * 3 # x中每一个元素都乘以3，等价于将3广播成np.array([3, 3])

array([3, 6])

x的shape为(2,)<br>
y的shape为(3,2)<br>
维数不相同，小维数的x先往左补1转换成(1,2)，再广播成(3,2)

In [14]:
x + a # x.shape:(2,)==>(1,2)==>(3,2)

array([[-1,  1],
       [ 1,  3],
       [ 3,  5]])

In [15]:
y = np.ones((3))
y + a # y.shape: (3,)==>(1,3)，无法继续广播

ValueError: operands could not be broadcast together with shapes (3,) (3,2) 