In [1]:
import numpy as np

# 1.常用聚合函数

In [2]:
x = np.random.rand(3, 2)
x

array([[0.2168402 , 0.42769279],
       [0.7085742 , 0.51875333],
       [0.47227293, 0.7218452 ]])

In [3]:
np.sum(x), np.mean(x) # 和值、平均值

(3.0659786430010967, 0.5109964405001828)

In [4]:
np.min(x), np.max(x) # 最小值、最大值

(0.2168402018991754, 0.721845200558901)

In [5]:
np.median(x), np.percentile(x, 20) # 中位数、百分之20分位数

(0.4955131265517152, 0.4276927907256044)

# 2.多维度聚合

In [6]:
np.max(x, axis=0) # 行间进行比较，axis=0即行这个维度消失

array([0.7085742, 0.7218452])

In [7]:
y = np.random.randn(2, 3, 4)
y

array([[[ 0.27019913,  1.22952022, -0.99375161, -0.61742665],
        [ 0.90598262, -0.66981778, -0.66845326, -1.13019331],
        [ 0.11086787, -0.57050249,  0.23728274,  0.1832871 ]],

       [[-0.00488559, -1.18939902,  0.15996435,  0.40170795],
        [-0.18645715,  0.02597251,  0.93365731, -3.2341283 ],
        [-0.76861096, -0.44554023,  2.63425843,  1.48762381]]])

In [8]:
y.sum(axis=1) # 另一种写法，axis=1的维度消失

array([[ 1.28704962, -0.01080005, -1.42492213, -1.56433286],
       [-0.9599537 , -1.60896674,  3.72788009, -1.34479654]])