In [1]:
import numpy as np

# 1.比较得到bool型数组

In [2]:
x = np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [3]:
x < 3 # 各个元素是否小于3

array([ True,  True,  True, False, False, False])

In [4]:
(2 ** x) == (x ** 2) # 各个元素是否满足等式

array([False, False,  True, False,  True, False])

In [5]:
np.sum(x >= 1) # 大于等于1的元素个数

5

In [6]:
np.any(x == 0) # 是否有元素为0

True

In [7]:
np.all(x > 0) # 是否所有元素都大于0

False

# 2.多个条件

In [8]:
(x >= 1) & (x <= 4) # 是否是[1, 4]间的数

array([False,  True,  True,  True,  True, False])

# 3.bool型数组作为索引

In [9]:
x[~((x > 4) | (x <= 2)) ]

array([3, 4])

# 4.排序

In [10]:
np.random.seed(0)
a = np.random.randint(0, 10, 5)
a

array([5, 0, 3, 3, 7])

In [11]:
np.sort(a) # 将a排序后数组，原数组a未改变

array([0, 3, 3, 5, 7])

In [12]:
np.argsort(a) # 从小到大的元素索引值

array([1, 2, 3, 0, 4])

In [13]:
a[np.argsort(a)] # 使用np.argsort(a)作为索引

array([0, 3, 3, 5, 7])

In [14]:
a.sort() # 排序并改变原数组
a

array([0, 3, 3, 5, 7])